services:
  - type: web
    name: DingDong-New-Code
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        value: your-token-here
      - key: AI_KEY
        value: your-ai-key-here
