services:
  - type: web
    name: DingDong-New-Code
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: DISCORD_BOT_TOKEN
        value: ${DISCORD_BOT_TOKEN}
      - key: AI_KEY
        value: ${AI_KEY}
